### PR TITLE
Eunit99 branch

### PR DESCRIPTION
**Pull request by Eunit99**
Updated most files and also created `jobseekers` component.
@leanny01 kindly take a look for necessary corrections.

### CODE REVIEW

**Review by leanny01 — CHANGES_REQUESTED** [review]
Weldone for the hard work, there are one or two things that I believe we could learn from a few mistakes in this PR


- It is recommended to have a branch name that describes what the branch is about. The name tells what the branch is about; in your case, you have given it your name. Here is an example, let say your branch is about building a job seeker component, the resulting branch can be named `jobSeekersComponent` 
- When working on a branch it is recommended to focus on code that has to do with the ticket, this will prevent code conflict during the merge process. You have mixed code from different tickets; I suggest you make another PR to fix code elsewhere.

I suggest you rename the branch so that we know what the code within does.

**Comment by Eunit99** [comment]
Thanks @leanny01 for the insight. Will do the corrections.

**Comment by Eunit99** [comment]
May I suggest that you merge this PR and from the subsequent ones, I will observe your guidelines. Thanks.

**Comment by leanny01** [comment]
Awesome, good job @Eunit99.

**Pull request merged**
